services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - "13378:80"
    volumes:
      - /home/marthynas/sambashare/personal/audiobooks:/audiobooks:ro
      - /srv/docker/audiobookshelf/config:/config
      - /srv/docker/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/Vilnius
