#!/bin/bash

BACKUP_DIR="$BACKUP_DIR"
RCLONE_CONFIG_PATH="$RCLONE_CONFIG_PATH"
RESTIC_PASSWORD_VALUE="$RESTIC_PASSWORD"

sudo rsync -av --delete /home/marthynas/.local/share/Terraria/ /srv/terraria-files/

echo "Shutting down docker containers"
docker-shutdown

echo "Creating backup..."
sudo RCLONE_CONFIG="$RCLONE_CONFIG_PATH" RESTIC_PASSWORD="$RESTIC_PASSWORD_VALUE" \
    restic -r "$(RESTIC_REPO)" backup /srv/

echo "Removing old backups..."
sudo RCLONE_CONFIG="$RCLONE_CONFIG_PATH" RESTIC_PASSWORD="$RESTIC_PASSWORD_VALUE" \
    restic -r "$(RESTIC_REPO)" forget --keep-daily 14 --prune

echo "Backup finished:)"
docker-up
